### ISSUE TITLE
Reading and writing userImages is broken

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#227]
Somewhere in the chaos, we've lost the ability to read/write to our `userImages` collection:

We are getting an error like:
```
Error updating image FirebaseError: Missing or insufficient permissions.
    at new n (http://localhost:8080/dist/app.js:21807:23)
    at http://localhost:8080/dist/app.js:36721:34
    at Y.<anonymous> (http://localhost:8080/dist/app.js:36676:21)
    at ub (http://localhost:8080/dist/app.js:39857:22)
    at Y../node_modules/@firebase/webchannel-wrapper/dist/index.esm.js.g.dispatchEvent (http://localhost:8080/dist/app.js:39837:50)
    at Z../node_modules/@firebase/webchannel-wrapper/dist/index.esm.js.Z.ma (http://localhost:8080/dist/app.js:40755:40)
    at nc (http://localhost:8080/dist/app.js:40125:138)
    at qc (http://localhost:8080/dist/app.js:40027:9)
    at H../node_modules/@firebase/webchannel-wrapper/dist/index.esm.js.g.ya (http://localhost:8080/dist/app.js:40002:35)
    at H../node_modules/@firebase/webchannel-wrapper/dist/index.esm.js.g.Sa (http://localhost:8080/dist/app.js:39967:84)
```

For both reads and writes

**Comment by aidan-fitz** [comment]
I don't see the `userImages` collection in Firebase Console. Must have been deleted.

**Comment by ibeckermayer** [comment]
Yeah, it was deleted when I ran `reset-infrastructure.js`

**Comment by aidan-fitz** [comment]
`reset-infrastructure.js` deletes but doesn't re-create the `userImages` collection. I assume re-creating it would solve the problem.
